import Link from 'next/link'

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#faf8f4', padding: '80px 40px' }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,700;1,300&family=DM+Sans:wght@300;400;500&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
      `}</style>

      <div style={{ maxWidth: '680px', margin: '0 auto' }}>
        {/* Back */}
        <Link href="/auth/signin" style={{ fontFamily: "'DM Sans',sans-serif", fontSize: '13px', color: 'rgba(26,22,18,0.42)', textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: '5px', marginBottom: '48px' }}>
          ← Back
        </Link>

        <h1 style={{ fontFamily: "'Cormorant Garamond',serif", fontSize: '40px', fontWeight: 700, color: '#1a1612', marginBottom: '8px', lineHeight: 1.1 }}>
          Terms of Service
        </h1>
        <p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: '13px', color: 'rgba(26,22,18,0.38)', marginBottom: '48px' }}>
          Last updated: June 2025 · thisWay (thiswayletsgo.com)
        </p>

        {[
          {
            title: 'Acceptance of Terms',
            body: 'By accessing or using ThisWay, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.',
          },
          {
            title: 'Use of Service',
            body: 'ThisWay provides AI-powered travel itinerary planning. The service is provided for personal, non-commercial use. You agree not to misuse the service or attempt to access it in unauthorised ways.',
          },
          {
            title: 'User Accounts',
            body: 'You are responsible for maintaining the security of your account. We use Google OAuth and email magic links — no passwords are stored. Notify us immediately of any unauthorised access.',
          },
          {
            title: 'Generated Content',
            body: 'Itineraries generated by ThisWay are AI-assisted suggestions and may not always reflect current conditions, pricing, or availability. Always verify critical travel information independently.',
          },
          {
            title: 'Limitation of Liability',
            body: 'ThisWay is not liable for travel disruptions, losses, or decisions made based on AI-generated content. Use our itineraries as a starting point, not as guaranteed plans.',
          },
          {
            title: 'Changes to Terms',
            body: 'We may update these terms periodically. Continued use of the service after changes constitutes acceptance of the updated terms.',
          },
          {
            title: 'Contact',
            body: 'Questions about these terms? Email us at hello@thiswayletsgo.com.',
          },
        ].map((s, i) => (
          <div key={i} style={{ marginBottom: '36px', paddingBottom: '36px', borderBottom: i < 6 ? '1px solid rgba(0,0,0,0.06)' : 'none' }}>
            <h2 style={{ fontFamily: "'Cormorant Garamond',serif", fontSize: '20px', fontWeight: 700, color: '#1a1612', marginBottom: '10px' }}>{s.title}</h2>
            <p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: '15px', color: 'rgba(26,22,18,0.62)', lineHeight: 1.75, fontWeight: 300 }}>{s.body}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
